services:
  dashdns:
    container_name: dashdns
    image: dasdns:v1
    privileged: true
    command: "/dashdns/dnsd -ip-blocklist='192.168.65.1:www.facebook.com'  -iface eth0"
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf:rw
      - /sys/kernel/debug:/sys/kernel/debug:ro
    ports:
      - "8888:53/udp"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_RESOURCE